name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
      - main
jobs:
  # Check:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Code check
  #       run: yarn lint
  Deploy-Preview:
    # needs: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  Deploy-Prod:
    needs: Deploy-Preview
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: DigitalDream-dev
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1
          issue-title: "Deploying to Prod"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
