
name: PR check
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  codeCheck:
    runs-on: ubuntu-latest
    steps: 
      - name: Code check
        run: yarn lint
  Deploy-Prod:
    needs: Deploy-Preview
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: DigitalDream-dev
          secret: ${{ github.TOKEN }}
          minimum-approvals: 1
          issue-title: "Deploying to Prod"
          issue-body: "Please approve or deny the deployment"
          exclude-workflow-initiator-as-approver: false
  
