
name: PR check
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  codeCheck:
    runs-on: ubuntu-latest
    environment: Preview – vercel-deploy
    steps: 
      - name: Code check
        run: yarn lint

  
