
name: PR check
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  code check:
    runs-on: ubuntu-latest
    steps: 
      - name: Code check
        run: yarn lint
